name: Firebase Model

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/

      - name: Install Dependencies
        run: npm install

      - name: Build package
        run: npm run build

      - run: echo "registry=https://npm.pkg.github.com/@Kushalkhadka7" >> .npmrc

      - name: Publish new release
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
