name: Firebase Model

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install Dependencies
        run: yarn

      - name: Build package
        run: yarn build
